version: '3.7'

services:

  laravel-cnab:
    build: .
    container_name: laravel-cnab
    tty: true
    volumes:
      - .:/var/www
    networks:
      - laravel-cnab-network

networks:
  laravel-cnab-network:
    driver: bridge
